# Generated by Django 4.2.7 on 2023-11-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
