# Generated by Django 4.2.7 on 2023-11-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_location_user_organization_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Donors',
        ),
    ]
